/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import java.io.Serializable;

/**
 * Address information
 */
@JsonDeserialize(builder = Address.Builder.class)
public class Address  implements Serializable {
  /**
   * Street name
   */
  private final String street;  // Default value is: null

  /**
   * Postal code
   */
  private final String postalCode;  // Default value is: null

  /**
   * City
   */
  private final String city;  // Default value is: null

  /**
   * Country
   */
  private final String country;  // Default value is: null

  private Address(Builder builder) {
      street = builder.street;
      postalCode = builder.postalCode;
      city = builder.city;
      country = builder.country;
  }

      /**
      * Street name
      * @return street
      **/
      public String getStreet() {return street;}

      /**
      * Postal code
      * @return postalCode
      **/
      public String getPostalCode() {return postalCode;}

      /**
      * City
      * @return city
      **/
      public String getCity() {return city;}

      /**
      * Country
      * @return country
      **/
      public String getCountry() {return country;}


  public static final class Builder {
      private String street;
      private String postalCode;
      private String city;
      private String country;

    public Builder() {
    }

    public Builder(Address copy) {
        this.street = copy.getStreet();
        this.postalCode = copy.getPostalCode();
        this.city = copy.getCity();
        this.country = copy.getCountry();
    }

    public Builder withStreet(String street) {
      this.street = street;
      return this;
    }

    public Builder withPostalCode(String postalCode) {
      this.postalCode = postalCode;
      return this;
    }

    public Builder withCity(String city) {
      this.city = city;
      return this;
    }

    public Builder withCountry(String country) {
      this.country = country;
      return this;
    }


    public Address build() { return new Address(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.street, address.street) &&
        Objects.equals(this.postalCode, address.postalCode) &&
        Objects.equals(this.city, address.city) &&
        Objects.equals(this.country, address.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(street, postalCode, city, country);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
