/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import io.idfy.deposit.models.DepositSummary;
import io.idfy.deposit.models.Links;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * CollectionWithPagingDepositSummary
 */
@JsonDeserialize(builder = CollectionWithPagingDepositSummary.Builder.class)
public class CollectionWithPagingDepositSummary  implements Serializable {
  private final Long size;  // Default value is: null

  private final Links links;  // Default value is: null

  private final Integer offset;  // Default value is: null

  private final Integer limit;  // Default value is: null

  private final List<DepositSummary> data;  // Default value is: new ArrayList<>()

  private CollectionWithPagingDepositSummary(Builder builder) {
      size = builder.size;
      links = builder.links;
      offset = builder.offset;
      limit = builder.limit;
      data = builder.data;
  }

      /**
      * Get size
      * @return size
      **/
      public Long getSize() {return size;}

      /**
      * Get links
      * @return links
      **/
      public Links getLinks() {return links;}

      /**
      * Get offset
      * @return offset
      **/
      public Integer getOffset() {return offset;}

      /**
      * Get limit
      * @return limit
      **/
      public Integer getLimit() {return limit;}

      /**
      * Get data
      * @return data
      **/
      public List<DepositSummary> getData() {return data;}


  public static final class Builder {
      private Long size;
      private Links links;
      private Integer offset;
      private Integer limit;
      private List<DepositSummary> data;

    public Builder() {
    }

    public Builder(CollectionWithPagingDepositSummary copy) {
        this.size = copy.getSize();
        this.links = copy.getLinks();
        this.offset = copy.getOffset();
        this.limit = copy.getLimit();
        this.data = copy.getData();
    }

    public Builder withSize(Long size) {
      this.size = size;
      return this;
    }

    public Builder withLinks(Links links) {
      this.links = links;
      return this;
    }

    public Builder withOffset(Integer offset) {
      this.offset = offset;
      return this;
    }

    public Builder withLimit(Integer limit) {
      this.limit = limit;
      return this;
    }

    public Builder withData(List<DepositSummary> data) {
      this.data = data;
      return this;
    }

    public Builder addDataItem(DepositSummary dataItem) {
      if (this.data == null) {
        this.data = new ArrayList<>();
      }
      this.data.add(dataItem);
      return this;
    }


    public CollectionWithPagingDepositSummary build() { return new CollectionWithPagingDepositSummary(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CollectionWithPagingDepositSummary collectionWithPagingDepositSummary = (CollectionWithPagingDepositSummary) o;
    return Objects.equals(this.size, collectionWithPagingDepositSummary.size) &&
        Objects.equals(this.links, collectionWithPagingDepositSummary.links) &&
        Objects.equals(this.offset, collectionWithPagingDepositSummary.offset) &&
        Objects.equals(this.limit, collectionWithPagingDepositSummary.limit) &&
        Objects.equals(this.data, collectionWithPagingDepositSummary.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(size, links, offset, limit, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CollectionWithPagingDepositSummary {\n");
    
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
