/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import java.io.Serializable;

/**
 * The data that will be signed.
 */
@JsonDeserialize(builder = DataToSign.Builder.class)
public class DataToSign  implements Serializable {
  /**
   * Base64-encoded string of the document, UTF-8-encoded.
   */
  private final String rentContractPDF;  // Default value is: null

  private DataToSign(Builder builder) {
      rentContractPDF = builder.rentContractPDF;
  }

      /**
      * Base64-encoded string of the document, UTF-8-encoded.
      * @return rentContractPDF
      **/
      public String getRentContractPDF() {return rentContractPDF;}


  public static final class Builder {
      private String rentContractPDF;

    public Builder() {
    }

    public Builder(DataToSign copy) {
        this.rentContractPDF = copy.getRentContractPDF();
    }

    public Builder withRentContractPDF(String rentContractPDF) {
      this.rentContractPDF = rentContractPDF;
      return this;
    }


    public DataToSign build() { return new DataToSign(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataToSign dataToSign = (DataToSign) o;
    return Objects.equals(this.rentContractPDF, dataToSign.rentContractPDF);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rentContractPDF);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataToSign {\n");
    
    sb.append("    rentContractPDF: ").append(toIndentedString(rentContractPDF)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
