/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * Domains allowed to iframe the generated url, required for &#x60;iframe&#x60; flow.
 */
@JsonDeserialize(builder = IFrameSettings.Builder.class)
public class IFrameSettings  implements Serializable {
  /**
   * Domains allowed to send <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage\" target=\"_blank\">webMessages</a> to
   */
  private final String postMessageTargetOrigin;  // Default value is: null

  /**
   * The domain(s) your website is hosted on
   */
  private final List<String> parentDomains;  // Default value is: new ArrayList<>()

  private IFrameSettings(Builder builder) {
      postMessageTargetOrigin = builder.postMessageTargetOrigin;
      parentDomains = builder.parentDomains;
  }

      /**
      * Domains allowed to send <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage\" target=\"_blank\">webMessages</a> to
      * @return postMessageTargetOrigin
      **/
      public String getPostMessageTargetOrigin() {return postMessageTargetOrigin;}

      /**
      * The domain(s) your website is hosted on
      * @return parentDomains
      **/
      public List<String> getParentDomains() {return parentDomains;}


  public static final class Builder {
      private String postMessageTargetOrigin;
      private List<String> parentDomains;

    public Builder() {
    }

    public Builder(IFrameSettings copy) {
        this.postMessageTargetOrigin = copy.getPostMessageTargetOrigin();
        this.parentDomains = copy.getParentDomains();
    }

    public Builder withPostMessageTargetOrigin(String postMessageTargetOrigin) {
      this.postMessageTargetOrigin = postMessageTargetOrigin;
      return this;
    }

    public Builder withParentDomains(List<String> parentDomains) {
      this.parentDomains = parentDomains;
      return this;
    }

    public Builder addParentDomainsItem(String parentDomainsItem) {
      this.parentDomains.add(parentDomainsItem);
      return this;
    }


    public IFrameSettings build() { return new IFrameSettings(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IFrameSettings iframeSettings = (IFrameSettings) o;
    return Objects.equals(this.postMessageTargetOrigin, iframeSettings.postMessageTargetOrigin) &&
        Objects.equals(this.parentDomains, iframeSettings.parentDomains);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postMessageTargetOrigin, parentDomains);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IFrameSettings {\n");
    
    sb.append("    postMessageTargetOrigin: ").append(toIndentedString(postMessageTargetOrigin)).append("\n");
    sb.append("    parentDomains: ").append(toIndentedString(parentDomains)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
