/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import io.idfy.deposit.models.Address;
import java.io.Serializable;

/**
 * LandlordResponse
 */
@JsonDeserialize(builder = LandlordResponse.Builder.class)
public class LandlordResponse  implements Serializable {
  private final String name;  // Default value is: null

  /**
   * Organization number if this was specified
   */
  private final String organizationNumber;  // Default value is: null

  private final Address address;  // Default value is: null

  /**
   * Ssn if this was specified
   */
  private final String ssn;  // Default value is: null

  private final String nationality;  // Default value is: null

  /**
   * Signature url for the landlord if `RepresentativeSignature` was specified.
   */
  private final String signUrl;  // Default value is: null

  private LandlordResponse(Builder builder) {
      name = builder.name;
      organizationNumber = builder.organizationNumber;
      address = builder.address;
      ssn = builder.ssn;
      nationality = builder.nationality;
      signUrl = builder.signUrl;
  }

      /**
      * Get name
      * @return name
      **/
      public String getName() {return name;}

      /**
      * Organization number if this was specified
      * @return organizationNumber
      **/
      public String getOrganizationNumber() {return organizationNumber;}

      /**
      * Get address
      * @return address
      **/
      public Address getAddress() {return address;}

      /**
      * Ssn if this was specified
      * @return ssn
      **/
      public String getSsn() {return ssn;}

      /**
      * Get nationality
      * @return nationality
      **/
      public String getNationality() {return nationality;}

      /**
      * Signature url for the landlord if `RepresentativeSignature` was specified.
      * @return signUrl
      **/
      public String getSignUrl() {return signUrl;}


  public static final class Builder {
      private String name;
      private String organizationNumber;
      private Address address;
      private String ssn;
      private String nationality;
      private String signUrl;

    public Builder() {
    }

    public Builder(LandlordResponse copy) {
        this.name = copy.getName();
        this.organizationNumber = copy.getOrganizationNumber();
        this.address = copy.getAddress();
        this.ssn = copy.getSsn();
        this.nationality = copy.getNationality();
        this.signUrl = copy.getSignUrl();
    }

    public Builder withName(String name) {
      this.name = name;
      return this;
    }

    public Builder withOrganizationNumber(String organizationNumber) {
      this.organizationNumber = organizationNumber;
      return this;
    }

    public Builder withAddress(Address address) {
      this.address = address;
      return this;
    }

    public Builder withSsn(String ssn) {
      this.ssn = ssn;
      return this;
    }

    public Builder withNationality(String nationality) {
      this.nationality = nationality;
      return this;
    }

    public Builder withSignUrl(String signUrl) {
      this.signUrl = signUrl;
      return this;
    }


    public LandlordResponse build() { return new LandlordResponse(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LandlordResponse landlordResponse = (LandlordResponse) o;
    return Objects.equals(this.name, landlordResponse.name) &&
        Objects.equals(this.organizationNumber, landlordResponse.organizationNumber) &&
        Objects.equals(this.address, landlordResponse.address) &&
        Objects.equals(this.ssn, landlordResponse.ssn) &&
        Objects.equals(this.nationality, landlordResponse.nationality) &&
        Objects.equals(this.signUrl, landlordResponse.signUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, organizationNumber, address, ssn, nationality, signUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LandlordResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationNumber: ").append(toIndentedString(organizationNumber)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    ssn: ").append(toIndentedString(ssn)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    signUrl: ").append(toIndentedString(signUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
