/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import java.io.Serializable;

/**
 * Basic landlord info
 */
@JsonDeserialize(builder = LandlordSummary.Builder.class)
public class LandlordSummary  implements Serializable {
  /**
   * Name of the landlord
   */
  private final String name;  // Default value is: null

  private LandlordSummary(Builder builder) {
      name = builder.name;
  }

      /**
      * Name of the landlord
      * @return name
      **/
      public String getName() {return name;}


  public static final class Builder {
      private String name;

    public Builder() {
    }

    public Builder(LandlordSummary copy) {
        this.name = copy.getName();
    }

    public Builder withName(String name) {
      this.name = name;
      return this;
    }


    public LandlordSummary build() { return new LandlordSummary(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LandlordSummary landlordSummary = (LandlordSummary) o;
    return Objects.equals(this.name, landlordSummary.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LandlordSummary {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
