/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import io.idfy.deposit.models.Address;
import io.idfy.deposit.models.LandlordSignOptions;
import java.io.Serializable;

/**
 * Landlord information.
 */
@JsonDeserialize(builder = LandlordRequest.Builder.class)
public class LandlordRequest  implements Serializable {
  /**
   * Full name of the landlord
   */
  private final String name;  // Default value is: null

  /**
   * Optional organization number. Either this or `ssn` must be set.
   */
  private final String organizationNumber;  // Default value is: null

  private final Address address;  // Default value is: null

  /**
   * Optional Social security number.
   */
  private final String ssn;  // Default value is: null

  /**
   * Nationality
   */
  private final String nationality;  // Default value is: null

  private final LandlordSignOptions representativeSignature;  // Default value is: null

  private LandlordRequest(Builder builder) {
      name = builder.name;
      organizationNumber = builder.organizationNumber;
      address = builder.address;
      ssn = builder.ssn;
      nationality = builder.nationality;
      representativeSignature = builder.representativeSignature;
  }

      /**
      * Full name of the landlord
      * @return name
      **/
      public String getName() {return name;}

      /**
      * Optional organization number. Either this or `ssn` must be set.
      * @return organizationNumber
      **/
      public String getOrganizationNumber() {return organizationNumber;}

      /**
      * Get address
      * @return address
      **/
      public Address getAddress() {return address;}

      /**
      * Optional Social security number.
      * @return ssn
      **/
      public String getSsn() {return ssn;}

      /**
      * Nationality
      * @return nationality
      **/
      public String getNationality() {return nationality;}

      /**
      * Get representativeSignature
      * @return representativeSignature
      **/
      public LandlordSignOptions getRepresentativeSignature() {return representativeSignature;}


  public static final class Builder {
      private String name;
      private String organizationNumber;
      private Address address;
      private String ssn;
      private String nationality;
      private LandlordSignOptions representativeSignature;

    public Builder() {
    }

    public Builder(LandlordRequest copy) {
        this.name = copy.getName();
        this.organizationNumber = copy.getOrganizationNumber();
        this.address = copy.getAddress();
        this.ssn = copy.getSsn();
        this.nationality = copy.getNationality();
        this.representativeSignature = copy.getRepresentativeSignature();
    }

    public Builder withName(String name) {
      this.name = name;
      return this;
    }

    public Builder withOrganizationNumber(String organizationNumber) {
      this.organizationNumber = organizationNumber;
      return this;
    }

    public Builder withAddress(Address address) {
      this.address = address;
      return this;
    }

    public Builder withSsn(String ssn) {
      this.ssn = ssn;
      return this;
    }

    public Builder withNationality(String nationality) {
      this.nationality = nationality;
      return this;
    }

    public Builder withRepresentativeSignature(LandlordSignOptions representativeSignature) {
      this.representativeSignature = representativeSignature;
      return this;
    }


    public LandlordRequest build() { return new LandlordRequest(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LandlordRequest landlordRequest = (LandlordRequest) o;
    return Objects.equals(this.name, landlordRequest.name) &&
        Objects.equals(this.organizationNumber, landlordRequest.organizationNumber) &&
        Objects.equals(this.address, landlordRequest.address) &&
        Objects.equals(this.ssn, landlordRequest.ssn) &&
        Objects.equals(this.nationality, landlordRequest.nationality) &&
        Objects.equals(this.representativeSignature, landlordRequest.representativeSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, organizationNumber, address, ssn, nationality, representativeSignature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LandlordRequest {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationNumber: ").append(toIndentedString(organizationNumber)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    ssn: ").append(toIndentedString(ssn)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    representativeSignature: ").append(toIndentedString(representativeSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
