/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import io.idfy.deposit.models.LoanApplicationStatus;
import java.time.OffsetDateTime;
import java.io.Serializable;

/**
 * Loan application information when a tenant has applied for a loan
 */
@JsonDeserialize(builder = LoanApplication.Builder.class)
public class LoanApplication  implements Serializable {
  /**
   * The status of the loan
   */
  private final LoanApplicationStatus status;  // Default value is: null

  /**
   * Last check of the loan (ISO 8601)
   */
  private final OffsetDateTime lastCheck;  // Default value is: null

  private LoanApplication(Builder builder) {
      status = builder.status;
      lastCheck = builder.lastCheck;
  }

      /**
      * The status of the loan
      * @return status
      **/
      public LoanApplicationStatus getStatus() {return status;}

      /**
      * Last check of the loan (ISO 8601)
      * @return lastCheck
      **/
      public OffsetDateTime getLastCheck() {return lastCheck;}


  public static final class Builder {
      private LoanApplicationStatus status;
      private OffsetDateTime lastCheck;

    public Builder() {
    }

    public Builder(LoanApplication copy) {
        this.status = copy.getStatus();
        this.lastCheck = copy.getLastCheck();
    }

    public Builder withStatus(LoanApplicationStatus status) {
      this.status = status;
      return this;
    }

    public Builder withLastCheck(OffsetDateTime lastCheck) {
      this.lastCheck = lastCheck;
      return this;
    }


    public LoanApplication build() { return new LoanApplication(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanApplication loanApplication = (LoanApplication) o;
    return Objects.equals(this.status, loanApplication.status) &&
        Objects.equals(this.lastCheck, loanApplication.lastCheck);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, lastCheck);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanApplication {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastCheck: ").append(toIndentedString(lastCheck)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
