/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

 /**
   * The status of the loan
   */
  public enum LoanApplicationStatus {
	@JsonProperty("unknown")
    UNKNOWN("unknown"),
    
	@JsonProperty("pending")
    PENDING("pending"),
    
	@JsonProperty("paid_out")
    PAID_OUT("paid_out"),
    
	@JsonProperty("rejected")
    REJECTED("rejected");

    private String value;

    LoanApplicationStatus(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LoanApplicationStatus fromValue(String text) {
      for (LoanApplicationStatus b : LoanApplicationStatus.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }
