/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import java.io.Serializable;

/**
 * Settings used for navigating when lifecycle events occur, required for &#x60;redirect&#x60; flow.
 */
@JsonDeserialize(builder = RedirectSettings.Builder.class)
public class RedirectSettings  implements Serializable {
  /**
   * The URL that the person is redirected to if something goes wrong.
   */
  private final String error;  // Default value is: null

  /**
   * The URL that the person is redirected to if the signing is cancelled.
   */
  private final String cancel;  // Default value is: null

  /**
   * The URL that the person is redirected to after a successful signing.
   */
  private final String success;  // Default value is: null

  private RedirectSettings(Builder builder) {
      error = builder.error;
      cancel = builder.cancel;
      success = builder.success;
  }

      /**
      * The URL that the person is redirected to if something goes wrong.
      * @return error
      **/
      public String getError() {return error;}

      /**
      * The URL that the person is redirected to if the signing is cancelled.
      * @return cancel
      **/
      public String getCancel() {return cancel;}

      /**
      * The URL that the person is redirected to after a successful signing.
      * @return success
      **/
      public String getSuccess() {return success;}


  public static final class Builder {
      private String error;
      private String cancel;
      private String success;

    public Builder() {
    }

    public Builder(RedirectSettings copy) {
        this.error = copy.getError();
        this.cancel = copy.getCancel();
        this.success = copy.getSuccess();
    }

    public Builder withError(String error) {
      this.error = error;
      return this;
    }

    public Builder withCancel(String cancel) {
      this.cancel = cancel;
      return this;
    }

    public Builder withSuccess(String success) {
      this.success = success;
      return this;
    }


    public RedirectSettings build() { return new RedirectSettings(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedirectSettings redirectSettings = (RedirectSettings) o;
    return Objects.equals(this.error, redirectSettings.error) &&
        Objects.equals(this.cancel, redirectSettings.cancel) &&
        Objects.equals(this.success, redirectSettings.success);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, cancel, success);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedirectSettings {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    cancel: ").append(toIndentedString(cancel)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
