/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import java.io.Serializable;

/**
 * Additional information to add to the bank transfer
 */
@JsonDeserialize(builder = ReleaseInfoLandlord.Builder.class)
public class ReleaseInfoLandlord  implements Serializable {
  /**
   * KID number for the transfer
   */
  private final String kid;  // Default value is: null

  /**
   * Description message for the transfer
   */
  private final String description;  // Default value is: null

  private ReleaseInfoLandlord(Builder builder) {
      kid = builder.kid;
      description = builder.description;
  }

      /**
      * KID number for the transfer
      * @return kid
      **/
      public String getKid() {return kid;}

      /**
      * Description message for the transfer
      * @return description
      **/
      public String getDescription() {return description;}


  public static final class Builder {
      private String kid;
      private String description;

    public Builder() {
    }

    public Builder(ReleaseInfoLandlord copy) {
        this.kid = copy.getKid();
        this.description = copy.getDescription();
    }

    public Builder withKid(String kid) {
      this.kid = kid;
      return this;
    }

    public Builder withDescription(String description) {
      this.description = description;
      return this;
    }


    public ReleaseInfoLandlord build() { return new ReleaseInfoLandlord(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReleaseInfoLandlord releaseInfoLandlord = (ReleaseInfoLandlord) o;
    return Objects.equals(this.kid, releaseInfoLandlord.kid) &&
        Objects.equals(this.description, releaseInfoLandlord.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kid, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReleaseInfoLandlord {\n");
    
    sb.append("    kid: ").append(toIndentedString(kid)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
