/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import java.io.Serializable;

/**
 * Release amount for SPLIT category
 */
@JsonDeserialize(builder = ReleaseAmount.Builder.class)
public class ReleaseAmount  implements Serializable {
  /**
   * Amount released to the tenant
   */
  private final Double tenant;  // Default value is: null

  /**
   * Amount released to the landlord
   */
  private final Double landlord;  // Default value is: null

  private ReleaseAmount(Builder builder) {
      tenant = builder.tenant;
      landlord = builder.landlord;
  }

      /**
      * Amount released to the tenant
      * @return tenant
      **/
      public Double getTenant() {return tenant;}

      /**
      * Amount released to the landlord
      * @return landlord
      **/
      public Double getLandlord() {return landlord;}


  public static final class Builder {
      private Double tenant;
      private Double landlord;

    public Builder() {
    }

    public Builder(ReleaseAmount copy) {
        this.tenant = copy.getTenant();
        this.landlord = copy.getLandlord();
    }

    public Builder withTenant(Double tenant) {
      this.tenant = tenant;
      return this;
    }

    public Builder withLandlord(Double landlord) {
      this.landlord = landlord;
      return this;
    }


    public ReleaseAmount build() { return new ReleaseAmount(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReleaseAmount releaseAmount = (ReleaseAmount) o;
    return Objects.equals(this.tenant, releaseAmount.tenant) &&
        Objects.equals(this.landlord, releaseAmount.landlord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenant, landlord);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReleaseAmount {\n");
    
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    landlord: ").append(toIndentedString(landlord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
