/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

 /**
   * Status of the deposit
   */
  public enum StatusDepositStatus {
	@JsonProperty("CREATED")
    CREATED("CREATED"),
    
	@JsonProperty("PAID")
    PAID("PAID"),
    
	@JsonProperty("PAID_PARTIAL")
    PAID_PARTIAL("PAID_PARTIAL"),
    
	@JsonProperty("TERMINATED")
    TERMINATED("TERMINATED"),
    
	@JsonProperty("SIGNED")
    SIGNED("SIGNED");

    private String value;

    StatusDepositStatus(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusDepositStatus fromValue(String text) {
      for (StatusDepositStatus b : StatusDepositStatus.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }
