/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import io.idfy.deposit.models.StatusDepositStatus;
import java.time.OffsetDateTime;
import java.io.Serializable;

/**
 * Overall status of the deposit
 */
@JsonDeserialize(builder = Status.Builder.class)
public class Status  implements Serializable {
  /**
   * Status of the deposit
   */
  private final StatusDepositStatus depositStatus;  // Default value is: null

  /**
   * Amount of funds in the deposit
   */
  private final Double funds;  // Default value is: null

  /**
   * Date the deposit was last checked for funds (ISO 8601)
   */
  private final OffsetDateTime lastPaymentCheck;  // Default value is: null

  private Status(Builder builder) {
      depositStatus = builder.depositStatus;
      funds = builder.funds;
      lastPaymentCheck = builder.lastPaymentCheck;
  }

      /**
      * Status of the deposit
      * @return depositStatus
      **/
      public StatusDepositStatus getDepositStatus() {return depositStatus;}

      /**
      * Amount of funds in the deposit
      * @return funds
      **/
      public Double getFunds() {return funds;}

      /**
      * Date the deposit was last checked for funds (ISO 8601)
      * @return lastPaymentCheck
      **/
      public OffsetDateTime getLastPaymentCheck() {return lastPaymentCheck;}


  public static final class Builder {
      private StatusDepositStatus depositStatus;
      private Double funds;
      private OffsetDateTime lastPaymentCheck;

    public Builder() {
    }

    public Builder(Status copy) {
        this.depositStatus = copy.getDepositStatus();
        this.funds = copy.getFunds();
        this.lastPaymentCheck = copy.getLastPaymentCheck();
    }

    public Builder withDepositStatus(StatusDepositStatus depositStatus) {
      this.depositStatus = depositStatus;
      return this;
    }

    public Builder withFunds(Double funds) {
      this.funds = funds;
      return this;
    }

    public Builder withLastPaymentCheck(OffsetDateTime lastPaymentCheck) {
      this.lastPaymentCheck = lastPaymentCheck;
      return this;
    }


    public Status build() { return new Status(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Status status = (Status) o;
    return Objects.equals(this.depositStatus, status.depositStatus) &&
        Objects.equals(this.funds, status.funds) &&
        Objects.equals(this.lastPaymentCheck, status.lastPaymentCheck);
  }

  @Override
  public int hashCode() {
    return Objects.hash(depositStatus, funds, lastPaymentCheck);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Status {\n");
    
    sb.append("    depositStatus: ").append(toIndentedString(depositStatus)).append("\n");
    sb.append("    funds: ").append(toIndentedString(funds)).append("\n");
    sb.append("    lastPaymentCheck: ").append(toIndentedString(lastPaymentCheck)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
