/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

 /**
   * The color theme for the application.
   */
  public enum StylingColorTheme {
	@JsonProperty("Default")
    DEFAULT("Default"),
    
	@JsonProperty("Black")
    BLACK("Black"),
    
	@JsonProperty("Blue")
    BLUE("Blue"),
    
	@JsonProperty("Cyan")
    CYAN("Cyan"),
    
	@JsonProperty("Dark")
    DARK("Dark"),
    
	@JsonProperty("Lime")
    LIME("Lime"),
    
	@JsonProperty("Neutral")
    NEUTRAL("Neutral"),
    
	@JsonProperty("Pink")
    PINK("Pink"),
    
	@JsonProperty("Purple")
    PURPLE("Purple"),
    
	@JsonProperty("Red")
    RED("Red"),
    
	@JsonProperty("Teal")
    TEAL("Teal"),
    
	@JsonProperty("Indigo")
    INDIGO("Indigo"),
    
	@JsonProperty("LightBlue")
    LIGHTBLUE("LightBlue"),
    
	@JsonProperty("DeepPurple")
    DEEPPURPLE("DeepPurple"),
    
	@JsonProperty("Green")
    GREEN("Green"),
    
	@JsonProperty("LightGreen")
    LIGHTGREEN("LightGreen"),
    
	@JsonProperty("Yellow")
    YELLOW("Yellow"),
    
	@JsonProperty("Amber")
    AMBER("Amber"),
    
	@JsonProperty("Orange")
    ORANGE("Orange"),
    
	@JsonProperty("DeepOrange")
    DEEPORANGE("DeepOrange"),
    
	@JsonProperty("Brown")
    BROWN("Brown"),
    
	@JsonProperty("Gray")
    GRAY("Gray"),
    
	@JsonProperty("BlueGray")
    BLUEGRAY("BlueGray"),
    
	@JsonProperty("OceanGreen")
    OCEANGREEN("OceanGreen"),
    
	@JsonProperty("GreenOcean")
    GREENOCEAN("GreenOcean");

    private String value;

    StylingColorTheme(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StylingColorTheme fromValue(String text) {
      for (StylingColorTheme b : StylingColorTheme.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }
