/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

 /**
   * The type of spinner to show in loading screens.
   */
  public enum StylingSpinner {
	@JsonProperty("Document")
    DOCUMENT("Document"),
    
	@JsonProperty("Classic")
    CLASSIC("Classic"),
    
	@JsonProperty("Cubes")
    CUBES("Cubes"),
    
	@JsonProperty("Bounce")
    BOUNCE("Bounce");

    private String value;

    StylingSpinner(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StylingSpinner fromValue(String text) {
      for (StylingSpinner b : StylingSpinner.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }
