/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import io.idfy.deposit.models.IFrameSettings;
import io.idfy.deposit.models.RedirectSettings;
import io.idfy.deposit.models.TenantInfo;
import io.idfy.deposit.models.TenantsResponseFlow;
import io.idfy.deposit.models.UI;
import java.io.Serializable;

/**
 * Tenant
 */
@JsonDeserialize(builder = Tenant.Builder.class)
public class Tenant  implements Serializable {
  /**
   * Your reference for the Tenant.
   */
  private final String externalId;  // Default value is: null

  /**
   * If AML is required
   */
  private final Boolean aml;  // Default value is: null

  private final TenantInfo info;  // Default value is: null

  private final UI ui;  // Default value is: null

  /**
   * Defines the flow to use.
   */
  private final TenantsResponseFlow flow;  // Default value is: null

  private final IFrameSettings iframeSettings;  // Default value is: null

  private final RedirectSettings redirectSettings;  // Default value is: null

  private Tenant(Builder builder) {
      externalId = builder.externalId;
      aml = builder.aml;
      info = builder.info;
      ui = builder.ui;
      flow = builder.flow;
      iframeSettings = builder.iframeSettings;
      redirectSettings = builder.redirectSettings;
  }

      /**
      * Your reference for the Tenant.
      * @return externalId
      **/
      public String getExternalId() {return externalId;}

      /**
      * If AML is required
      * @return aml
      **/
      public Boolean getAml() {return aml;}

      /**
      * Get info
      * @return info
      **/
      public TenantInfo getInfo() {return info;}

      /**
      * Get ui
      * @return ui
      **/
      public UI getUi() {return ui;}

      /**
      * Defines the flow to use.
      * @return flow
      **/
      public TenantsResponseFlow getFlow() {return flow;}

      /**
      * Get iframeSettings
      * @return iframeSettings
      **/
      public IFrameSettings getIframeSettings() {return iframeSettings;}

      /**
      * Get redirectSettings
      * @return redirectSettings
      **/
      public RedirectSettings getRedirectSettings() {return redirectSettings;}


  public static final class Builder {
      private String externalId;
      private Boolean aml;
      private TenantInfo info;
      private UI ui;
      private TenantsResponseFlow flow;
      private IFrameSettings iframeSettings;
      private RedirectSettings redirectSettings;

    public Builder() {
    }

    public Builder(Tenant copy) {
        this.externalId = copy.getExternalId();
        this.aml = copy.getAml();
        this.info = copy.getInfo();
        this.ui = copy.getUi();
        this.flow = copy.getFlow();
        this.iframeSettings = copy.getIframeSettings();
        this.redirectSettings = copy.getRedirectSettings();
    }

    public Builder withExternalId(String externalId) {
      this.externalId = externalId;
      return this;
    }

    public Builder withAml(Boolean aml) {
      this.aml = aml;
      return this;
    }

    public Builder withInfo(TenantInfo info) {
      this.info = info;
      return this;
    }

    public Builder withUi(UI ui) {
      this.ui = ui;
      return this;
    }

    public Builder withFlow(TenantsResponseFlow flow) {
      this.flow = flow;
      return this;
    }

    public Builder withIframeSettings(IFrameSettings iframeSettings) {
      this.iframeSettings = iframeSettings;
      return this;
    }

    public Builder withRedirectSettings(RedirectSettings redirectSettings) {
      this.redirectSettings = redirectSettings;
      return this;
    }


    public Tenant build() { return new Tenant(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tenant tenant = (Tenant) o;
    return Objects.equals(this.externalId, tenant.externalId) &&
        Objects.equals(this.aml, tenant.aml) &&
        Objects.equals(this.info, tenant.info) &&
        Objects.equals(this.ui, tenant.ui) &&
        Objects.equals(this.flow, tenant.flow) &&
        Objects.equals(this.iframeSettings, tenant.iframeSettings) &&
        Objects.equals(this.redirectSettings, tenant.redirectSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalId, aml, info, ui, flow, iframeSettings, redirectSettings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tenant {\n");
    
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    aml: ").append(toIndentedString(aml)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    ui: ").append(toIndentedString(ui)).append("\n");
    sb.append("    flow: ").append(toIndentedString(flow)).append("\n");
    sb.append("    iframeSettings: ").append(toIndentedString(iframeSettings)).append("\n");
    sb.append("    redirectSettings: ").append(toIndentedString(redirectSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
