/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import java.io.Serializable;

/**
 * Basic tenant info
 */
@JsonDeserialize(builder = TenantSummary.Builder.class)
public class TenantSummary  implements Serializable {
  /**
   * First name of the tenant
   */
  private final String firstName;  // Default value is: null

  /**
   * Last name of the tenant
   */
  private final String lastName;  // Default value is: null

  private TenantSummary(Builder builder) {
      firstName = builder.firstName;
      lastName = builder.lastName;
  }

      /**
      * First name of the tenant
      * @return firstName
      **/
      public String getFirstName() {return firstName;}

      /**
      * Last name of the tenant
      * @return lastName
      **/
      public String getLastName() {return lastName;}


  public static final class Builder {
      private String firstName;
      private String lastName;

    public Builder() {
    }

    public Builder(TenantSummary copy) {
        this.firstName = copy.getFirstName();
        this.lastName = copy.getLastName();
    }

    public Builder withFirstName(String firstName) {
      this.firstName = firstName;
      return this;
    }

    public Builder withLastName(String lastName) {
      this.lastName = lastName;
      return this;
    }


    public TenantSummary build() { return new TenantSummary(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TenantSummary tenantSummary = (TenantSummary) o;
    return Objects.equals(this.firstName, tenantSummary.firstName) &&
        Objects.equals(this.lastName, tenantSummary.lastName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TenantSummary {\n");
    
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
