/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

 /**
   * Termination category. Use TENANT to release the entire amount to the tenant.  In case of a SPLIT, provide the amounts to use.  DISPUTE=N/A
   */
  public enum TerminateRequestCategory {
	@JsonProperty("TENANT")
    TENANT("TENANT"),
    
	@JsonProperty("SPLIT")
    SPLIT("SPLIT"),
    
	@JsonProperty("DISPUTE")
    DISPUTE("DISPUTE");

    private String value;

    TerminateRequestCategory(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TerminateRequestCategory fromValue(String text) {
      for (TerminateRequestCategory b : TerminateRequestCategory.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }
