/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import io.idfy.deposit.models.ReleaseInfoLandlord;
import java.io.Serializable;

/**
 * Transaction information
 */
@JsonDeserialize(builder = TransactionInfo.Builder.class)
public class TransactionInfo  implements Serializable {
  private final ReleaseInfoLandlord landlord;  // Default value is: null

  private TransactionInfo(Builder builder) {
      landlord = builder.landlord;
  }

      /**
      * Get landlord
      * @return landlord
      **/
      public ReleaseInfoLandlord getLandlord() {return landlord;}


  public static final class Builder {
      private ReleaseInfoLandlord landlord;

    public Builder() {
    }

    public Builder(TransactionInfo copy) {
        this.landlord = copy.getLandlord();
    }

    public Builder withLandlord(ReleaseInfoLandlord landlord) {
      this.landlord = landlord;
      return this;
    }


    public TransactionInfo build() { return new TransactionInfo(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionInfo transactionInfo = (TransactionInfo) o;
    return Objects.equals(this.landlord, transactionInfo.landlord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(landlord);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionInfo {\n");
    
    sb.append("    landlord: ").append(toIndentedString(landlord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
