/*
 * Idfy Deposit
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */

package io.idfy.deposit.models;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;
import io.idfy.deposit.models.Styling;
import io.idfy.deposit.models.UILanguage;
import java.io.Serializable;

/**
 * UI settings for the deposit process.
 */
@JsonDeserialize(builder = UI.Builder.class)
public class UI  implements Serializable {
  /**
   * The tenants's preferred language. This language will be used when signing the document and in email/SMS notifications.
   */
  private final UILanguage language;  // Default value is: null

  private final Styling styling;  // Default value is: null

  private UI(Builder builder) {
      language = builder.language;
      styling = builder.styling;
  }

      /**
      * The tenants's preferred language. This language will be used when signing the document and in email/SMS notifications.
      * @return language
      **/
      public UILanguage getLanguage() {return language;}

      /**
      * Get styling
      * @return styling
      **/
      public Styling getStyling() {return styling;}


  public static final class Builder {
      private UILanguage language;
      private Styling styling;

    public Builder() {
    }

    public Builder(UI copy) {
        this.language = copy.getLanguage();
        this.styling = copy.getStyling();
    }

    public Builder withLanguage(UILanguage language) {
      this.language = language;
      return this;
    }

    public Builder withStyling(Styling styling) {
      this.styling = styling;
      return this;
    }


    public UI build() { return new UI(this); }
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UI UI = (UI) o;
    return Objects.equals(this.language, UI.language) &&
        Objects.equals(this.styling, UI.styling);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, styling);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UI {\n");
    
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    styling: ").append(toIndentedString(styling)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
