/*
 * Idfy JWT
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@idfy.io
 */


package io.idfy.jwt;

import io.idfy.OAuthScope;
import io.idfy.models.IdfyException;
import io.idfy.IdfyConfiguration;
import io.idfy.jwt.models.JwtValidationResultDto;
import io.idfy.jwt.models.ValidateJwtDto;
import java.io.InputStream;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.*;

/**
 * API tests for JwtService
 */

public class JwtServiceTest {
    // The service name still needs to be set manually
    List<OAuthScope> scopes = Arrays.asList(OAuthScope.DocumentRead, OAuthScope.DocumentWrite, OAuthScope.DocumentFile);
    private final JwtService api = new JwtService("clientId", "clientSecret", scopes);

    @BeforeAll
    public static void setUp() {
    IdfyConfiguration.setBaseUrl("http://localhost:5000");
    }

    
    /**
     * Validate JWT
     *
     * 
     */
    @Test
    public void jwtValidatePostTest() throws IdfyException, Exception {
        ValidateJwtDto request =  new ValidateJwtDto.Builder().build();
        JwtValidationResultDto response = api.jwtValidatePost(request);
        assertNotNull(response);
    }

}
